# -*- coding: utf-8 -*-
"""飞书登录用户表（users）：按 open_id UPSERT，保存资料与登录统计。

与"共享密码"登录（DASH_USER/DASH_PASSWORD）相互独立——密码登录不落这张表。
首次飞书登录自动建号；之后每次刷新 name/avatar/last_login_at 并 login_count+1。
"""
from typing import Optional

from ..db import get_conn

_DDL = """
CREATE TABLE IF NOT EXISTS users (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  open_id        text UNIQUE,
  union_id       text,
  feishu_user_id text,
  name           text,
  avatar_url     text,
  email          text,
  mobile         text,
  source         text DEFAULT 'feishu',
  is_active      boolean DEFAULT true,
  is_admin       boolean DEFAULT false,
  first_login_at timestamptz DEFAULT now(),
  last_login_at  timestamptz,
  login_count    int DEFAULT 0,
  created_at     timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now()
);
COMMENT ON TABLE users IS '飞书登录用户表（共享密码登录不落此表）';
COMMENT ON COLUMN users.id IS '自增主键';
COMMENT ON COLUMN users.open_id IS '飞书 open_id（UPSERT 键）';
COMMENT ON COLUMN users.union_id IS '飞书 union_id';
COMMENT ON COLUMN users.feishu_user_id IS '飞书 user_id';
COMMENT ON COLUMN users.name IS '姓名';
COMMENT ON COLUMN users.avatar_url IS '头像 URL';
COMMENT ON COLUMN users.email IS '邮箱';
COMMENT ON COLUMN users.mobile IS '手机号';
COMMENT ON COLUMN users.source IS '账号来源（feishu）';
COMMENT ON COLUMN users.is_active IS '是否允许登录（封禁置 false）';
COMMENT ON COLUMN users.is_admin IS '是否管理员（默认 false，需手工置位）';
COMMENT ON COLUMN users.first_login_at IS '首次登录时间';
COMMENT ON COLUMN users.last_login_at IS '最近登录时间';
COMMENT ON COLUMN users.login_count IS '累计登录次数';
COMMENT ON COLUMN users.created_at IS '建号时间';
COMMENT ON COLUMN users.updated_at IS '最近更新时间'"""


def _ensure(cur):
    cur.execute(_DDL)


def upsert_login(info: dict) -> Optional[dict]:
    """飞书回调里调用：按 open_id UPSERT，返回 {open_id, name, is_active}。
    open_id 缺失或落库失败返回 None（不阻断登录，调用方自行兜底）。"""
    open_id = info.get('open_id')
    if not open_id:
        return None
    try:
        with get_conn() as conn:
            cur = conn.cursor()
            _ensure(cur)
            cur.execute("""
                INSERT INTO users(open_id, union_id, feishu_user_id, name, avatar_url,
                                  email, mobile, source, last_login_at, login_count)
                VALUES (%s, %s, %s, %s, %s, %s, %s, 'feishu', now(), 1)
                ON CONFLICT (open_id) DO UPDATE SET
                    union_id = EXCLUDED.union_id,
                    feishu_user_id = EXCLUDED.feishu_user_id,
                    name = EXCLUDED.name,
                    avatar_url = EXCLUDED.avatar_url,
                    email = COALESCE(EXCLUDED.email, users.email),
                    mobile = COALESCE(EXCLUDED.mobile, users.mobile),
                    last_login_at = now(),
                    login_count = users.login_count + 1,
                    updated_at = now()
                RETURNING open_id, name, is_active""",
                (open_id, info.get('union_id'),
                 str(info.get('user_id') or '') or None, info.get('name'),
                 info.get('avatar_url'), info.get('email') or info.get('enterprise_email'),
                 info.get('mobile')))
            r = cur.fetchone()
            conn.commit()
            return {'open_id': r[0], 'name': r[1], 'is_active': r[2]} if r else None
    except Exception:      # noqa: BLE001 —— 落库失败不阻断登录
        return None


def get_by_open_id(open_id: str) -> Optional[dict]:
    if not open_id:
        return None
    try:
        with get_conn() as conn:
            cur = conn.cursor()
            _ensure(cur)
            conn.commit()
            cur.execute("""SELECT open_id, name, avatar_url, email, source, is_admin,
                                  is_active, login_count, last_login_at
                           FROM users WHERE open_id = %s""", (open_id,))
            r = cur.fetchone()
            if not r:
                return None
            cols = ['open_id', 'name', 'avatar_url', 'email', 'source', 'is_admin',
                    'is_active', 'login_count', 'last_login_at']
            d = dict(zip(cols, r))
            if d.get('last_login_at'):
                d['last_login_at'] = d['last_login_at'].strftime('%Y-%m-%d %H:%M')
            return d
    except Exception:      # noqa: BLE001
        return None


def display_name(open_id: str) -> str:
    """按 open_id 取显示名（用于操作记录）；查不到回退 open_id 前 8 位。"""
    u = get_by_open_id(open_id)
    if u and u.get('name'):
        return u['name']
    return (open_id or '')[:8] or '未知'


def list_all(limit: int = 500) -> list:
    """用户管理页：列出所有登录过的用户，最近登录在前。"""
    with get_conn() as conn:
        cur = conn.cursor()
        _ensure(cur)
        conn.commit()
        cur.execute("""SELECT open_id, name, avatar_url, email, mobile, source,
                              is_admin, is_active, login_count,
                              to_char(last_login_at,  'YYYY-MM-DD HH24:MI'),
                              to_char(first_login_at, 'YYYY-MM-DD HH24:MI')
                       FROM users
                       ORDER BY last_login_at DESC NULLS LAST, id DESC
                       LIMIT %s""", (limit,))
        cols = ['open_id', 'name', 'avatar_url', 'email', 'mobile', 'source',
                'is_admin', 'is_active', 'login_count', 'last_login_at', 'first_login_at']
        return [dict(zip(cols, r)) for r in cur.fetchall()]


def set_active(open_id: str, active: bool) -> bool:
    """启用/禁用某个飞书用户（禁用后其登录会被拦下）。返回是否命中记录。"""
    if not open_id:
        return False
    with get_conn() as conn:
        cur = conn.cursor()
        _ensure(cur)
        cur.execute('UPDATE users SET is_active = %s, updated_at = now() '
                    'WHERE open_id = %s', (bool(active), open_id))
        n = cur.rowcount
        conn.commit()
        return n > 0
